logging:
  level:
    com.lucasmedeiros.creditengine: DEBUG
    org.springframework.web: INFO

springdoc:
  swagger-ui:
    path: /swagger
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true